name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Stylua Format
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          version: 0.13.1
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua/
